stages:
 - mavenbuild
 - maventest
 - autodeploy
 - androidbuild

maven-build:
 stage: mavenbuild
 tags:
  - spring_tag
 script:
  - cd BackEnd
  - cd API
  - mvn package -B

maven-test:
 stage: maventest
 tags:
  -spring_tag
 script:
  - cd BackEnd
  - cd API
  - mvn test

auto-deploy:
 stage: autodeploy
 tags:
  - spring_tag
 script:
  - cd BackEnd
  - cd API
  - mvn package
  - sudo mv target/*.jar /target/web-demo.jar
  - sudo systemctl stop s-web-demo
  - sudo systemctl start s-web-demo

android-build:
 image: javiersantos/android-ci:latest
 stage: androidbuild
 before_script: 
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./FrontEnd/StudyBuddy/gradlew
 tags:
  - android_tag
 script:
  - cd FrontEnd
  - cd StudyBuddy
  - ./gradlew assemble